### PR TITLE
Code Review Request

### PR DESCRIPTION
**Pull request by cgcarlosg**
Code review request for the fourth project of the Microverse Program.
The project is done to practice the gradient and background images used in HTML and CSS3.
It is a clone of the webpage Apple.com

### CODE REVIEW

**Comment by cgcarlosg** [comment]
to tun linters

**Review by jubaan — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## :wave: :wave: Hello @cgcarlosg and @shahnaeem! Thanks for submitting!

Things to notice:
:100: the project uses the original images.
:100: The project mimics the appearance of the original site
:100: Using ```linear-gradient```
:100: Use of ```flex``` and ```float```

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [ ] Edit PR message to be more descriptive and meaningful. Don't use comments for the PR message.

- [ ] Linked in Link for ```cgcarlos``` doesn't have the correct link format. Sometimes takes to LinkedIn, but most of the time act as if it were broken.

- [ ] Issue link redirects to another project

- [ ] MIT license link is broken

- [ ] The navbar should be a ```<ul>``` with ```<li>``` elements. 

- [ ] All elements in the navbar should be links except for the search

- [ ] Use semantic HTML for the ```<main>``` section.

- [ ] Keep consistency in the alignment and indetation of the HTML file.

- [ ] Remove ```cursor: pointer``` and convert elements that use it to anchor tags in the HTML.

- [ ] Website should not have the gray margin
image

- [ ] Apple logo is not center vertically
image

- [ ] Text is not centered
image
image

- [ ] footer elements are not aligned

- [ ] footer is not centered
image

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

**Review by jubaan — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

Please review that all previously required changes are meet before submitting for a re-review.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

> # Status: Changes Required 
> ##   Hello @cgcarlosg and @shahnaeem! Thanks for submitting!
> Things to notice:
>  the project uses the original images.
>  The project mimics the appearance of the original site
>  Using `linear-gradient`
>  Use of `flex` and `float`
> 
> There are some issues that need to be addressed before we can move forward. Please review the list below.
> 
> ## Required changes 
> ### [Mandatory] 
- [ ]  **Edit PR message to be more descriptive and meaningful. Don't use comments for the PR message.**
> * [x]  Linked in Link for `cgcarlos` doesn't have the correct link format. Sometimes takes to LinkedIn, but most of the time act as if it were broken.
- [ ]  **Issue link redirects to another project. The NewYorkProject issue's page**
- [ ]  **MIT license link is broken. Links takes to 404 not found page**
> * [x]  The navbar should be a `<ul>` with `<li>` elements.
> * [x]  All elements in the navbar should be links except for the search
- [ ]  **Use semantic HTML for the `<main>` section.**
- [ ]  **Keep consistency in the alignment and indetation of the HTML file. see inline comments**
- [ ]  **Remove `cursor: pointer` from CSS file and convert elements that use it to anchor tags in the HTML.**
- [ ]  **Website should not have the gray margin. The website still has a margin around, the image should take full width**
>   image
> * [x]  Apple logo is not center vertically
>   image
> * [x]  Text is not centered
>   image
- [ ]  **footer elements are not aligned. firs line of footer is not aligned with the second line**
- [ ]  **footer is not centered. They have more margin on the left than in the right**
>   image
> 
> ## Keep up the great work  and Happy Coding  !!


## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
### Request changes 😳
I am very happy to see this project and I can see you worked hard on this project but I am sorry to inform you that I cannot approve this project because it is not completed yet. You need to work more on it. 
_It's okay. We are here to learn. Don't get discouraged. Work even harder. You are almost there.😄_
**Please have a look at the suggestions to get more understanding.**
- [ ] **Edit PR message to be more descriptive and meaningful. Don't use comments for the PR message. Please follow these steps to edit it.** 

1. Click on the three dots

chrome-capture (1)

2. Then click on edit

chrome-capture (2)

3. Update the message. 

- [ ] Keep consistency in the alignment and indentation of the HTML file. see inline comments

- [ ] Please make your commits message descriptive. This will help to understand what that commit is about. 

- [ ] issue link in the readme is not redirecting to the issue page. Please fix that. 

- [ ] As requested by previous TSEs to change the position of the logo to the center but you increase the size. Please work on it. 
chrome-capture (3)

- [ ] Please remove styling from the navbar links. 
chrome-capture (4)

- [ ] Your clone has horizontal scrolling please fix that. 


**Please make the changes and request re-review for the given project**
Stay safe and give me a smile 😇

### Happy Coding
---------------------------------------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

**Review by arslanbisharat — APPROVED** [review]
### Congratulations Approved 🎉
---------------------------------------------------------------------------------------------------------------

This project is approved with the latest changes you made. 

[OPTIONAL] If you wish to delete your currently working branch please update the Live demo link too so that it works properly. 

_Keep working hard._ 

**From now on, please make sure your commits are descriptive enough to understand.** 

I am very excited to see your next project.

**Happy Coding**:smiley:
------------------------------------------------------------------------------
**Regards,
Arslan Bisharat**
[linkedin](https://www.linkedin.com/in/arslanbisharat/) slack: @arslanbisharat

**Pull request closed without merging**
